#!/usr/bin/env bash
#
# Take a string variable (e.g. address:port) and split it by delimeter.
# This method works well only with simple strings which contains only one delimeter.

set -euxo pipefail

POSTGRES_ADDRESS=127.0.0.1:5432

echo ${POSTGRES_ADDRESS%:*}
