#!/bin/bash
#
# Different ways to compare a string.
# Kudos to https://linuxize.com/post/how-to-compare-strings-in-bash/

VAR=""
VAR1="V1"
VAR2="V2"

### 1. Full comparison.
# a. With single brackets.
if [ "$VAR1" = "$VAR2" ]; then
    echo "Strings are equal."
else
    echo "Strings are not equal."
fi

# b. With double brackets.
if [[ "$VAR1" == "$VAR2" ]]; then
    echo "Strings are equal."
else
    echo "Strings are not equal."
fi

# c. One-liner.
[[ "$VAR1" == "$VAR2" ]] && echo "Equal" || echo "Not equal"

### 2. Contains substring.
# a. Using asterisk symbols.
if [[ "$VAR1" == *"V"* ]]; then
  echo "It's there."
fi

# b. Using regexp operator.
if [[ "$VAR1" =~ .*V.* ]]; then
  echo "It's there."
fi


### 3. String is empty.
if [[ -z "$VAR" ]]; then
  echo "String is empty."
fi

### 4. String is not empty.
if [[ -n "$VAR1" ]]; then
  echo "String is not empty."
fi
